version: 0.0
os: linux
files:
  - source: /testing_docs/
    destination: /var/
permissions:
  - object: /var/testing_docs/
    owner: root
    group: root
    pattern: "*"
    mode: 775
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: /codeclear.sh
      runas: root
  AfterInstall:
    - location: /codepull.sh
      runas: root
